### ISSUE TITLE
TransposeDist error 

### ISSUE THREAD

**Issue by samadejacobs** [LLNL/lbann#508] opened 2018-07-09 17:03 UTC
I am observing this error "TransposeDist: This branch not implemented for device" when I run [candle pilot 1 combo](https://github.com/LLNL/lbann/blob/develop/model_zoo/models/candle/pilot1/combo.prototext) (model_parallel layout) on Pascal cluster. The error appear intermittently but also consistently on some node counts (e.g., N=1, 4) but not others (e.g., N=2, 8). The error doesn't show up with data_parallel layout on N=1  (haven't tried N=4) and it doesn't show up CPU-only cluster (Catalyst) at all, haven't tried on Surface yet.

**Comment by samadejacobs** [comment] 2018-07-09 18:09
The error appears to be coming from [this Gemm](https://github.com/LLNL/lbann/blob/develop/src/layers/learning/fully_connected.cpp) on both Pascal and Surface.

**Comment by timmoon10** [comment] 2018-07-09 18:46
This seems to arise from https://github.com/LLNL/Elemental/blob/feeefdcb8a1f99903ce5ad615bc8646de4fbdcd2/include/El/blas_like/level1/Copy/TransposeDist.hpp#L123.

**Comment by benson31** [comment] 2018-07-09 18:48
Yep. The issue is the EL_PARALLEL_FOR blocks that have not been ported to be GPU-friendly. I was waiting for someone to use this block of code before fixing it.

**Comment by samadejacobs** [comment] 2018-07-09 23:02
Yes, this is currently in use in pilot1 combo application.

**Comment by benson31** [comment] 2018-07-09 23:07
I'm working on a fix for GPU.

**Comment by davidHysom** [comment] 2018-07-09 23:14
>I was waiting for someone to use this block of code before fixing it

Ha.

I do this sort of thing a lot, but try to document it with  exceptions along the lines of:
  throw lbann_exception("this isn't working or needs implementation; please contact Dave Hysom");



________________________________

**Comment by timmoon10** [comment] 2018-07-30 23:29
This should be closed by https://github.com/LLNL/Elemental/pull/23.

**Closed by timmoon10** 2018-07-30 23:29 UTC
