### ISSUE TITLE
Weird memory imbalance on GPU

### ISSUE THREAD

**Issue by bvanessen** [LLNL/lbann#150] opened 2017-12-21 00:01 UTC
mpirun ../../../build/ray.llnl.gov/model_zoo/lbann --model=model_conv_molecular_autoencoder_pilot2.prototext --reader=../../data_readers/CANDLE/data_reader_candle_pilot2_3k_run16.prototext --o
ptimizer=../../optimizers/opt_adam.prototext

On Ray

[vanessen@ray12:~]$ nvidia-smi
Tue Dec 19 14:33:54 2017       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.59                 Driver Version: 384.59                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla P100-SXM2...  Off  | 00000002:01:00.0 Off |                    0 |
| N/A   34C    P0    42W / 300W |  13141MiB / 16276MiB |     19%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla P100-SXM2...  Off  | 00000003:01:00.0 Off |                    0 |
| N/A   33C    P0    42W / 300W |   3729MiB / 16276MiB |     16%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla P100-SXM2...  Off  | 00000006:01:00.0 Off |                    0 |
| N/A   35C    P0    42W / 300W |  13141MiB / 16276MiB |     21%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla P100-SXM2...  Off  | 00000007:01:00.0 Off |                    0 |
| N/A   34C    P0    39W / 300W |   3729MiB / 16276MiB |     20%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0    104710    C   ../../../build/ray.llnl.gov/model_zoo/lbann  13131MiB |
|    1    104710    C   ../../../build/ray.llnl.gov/model_zoo/lbann   3719MiB |
|    2    104710    C   ../../../build/ray.llnl.gov/model_zoo/lbann  13131MiB |
|    3    104710    C   ../../../build/ray.llnl.gov/model_zoo/lbann   3719MiB |
+-----------------------------------------------------------------------------+

**Comment by timmoon10** [comment] 2017-12-21 22:26
We should expect high GPU memory utilization since we allocate as large a workspace as possible. It seems that GPUs 0 and 2 are doing this correctly while GPUs 1 and 3 either fail to allocate a workspace or can only grab very small ones.

**Comment by bvanessen** [comment] 2017-12-22 01:00
Yes I expect the large memory it is the small ones that concern me.


Brian C. Van Essen

vanessen1@llnl.gov<mailto:vanessen1@llnl.gov>

(w) 925-422-9300

(c) 925-290-5470

---

Sent from my iPhone

On Dec 21, 2017, at 2:27 PM, Tim Moon <notifications@github.com<mailto:notifications@github.com>> wrote:


We should expect high GPU memory utilization since we allocate as large a workspace as possible. It seems that GPUs 0 and 2 are doing this correctly while GPUs 1 and 3 either fail to allocate a workspace or can only grab very small ones.

**Comment by naoyam** [comment] 2018-01-02 23:55
I'm trying to reproduce the problem, but I have a problem running the model itself. I'm using the latest commit on develop and the same command as originally mentioned by Brian. Here's the last part of the execution output:

```
Loading file: /p/gscratchr/brainusr/datasets/cancer/pilot2/3k_run16_10us.35fs-DPPC.20-DIPC.60-CHOL.20.dir/3k_run16_10us.35fs-DPPC.20-DIPC.60-CHOL.20_chunk_28_outof_29.npz
Loading file: /p/gscratchr/brainusr/datasets/cancer/pilot2/3k_run16_10us.35fs-DPPC.20-DIPC.60-CHOL.20.dir/3k_run16_10us.35fs-DPPC.20-DIPC.60-CHOL.20_chunk_29_outof_29.npz

**************************************************************************
 This lbann_exception is about to be thrown:/g/g92/maruyama/lbann/src/lbann/src/data_readers/data_reader_pilot2_molecular.cpp 53 pilot2_molecular::load() - no features

 Am now attemptting to print the stack trace ...
**************************************************************************
rank: 0 :: lbann::stack_trace::print_stack_trace()
rank: 0 :: lbann::stack_trace::print_lbann_exception_stack_trace(std::string)
rank: 0 :: lbann::lbann_exception::lbann_exception(std::string)
rank: 0 :: lbann::pilot2_molecular_reader::load()
rank: 0 :: lbann::data_reader_merge_samples::load()
rank: 0 :: init_data_readers(bool, lbann_data::LbannPB const&, std::map<execution_mode, lbann::generic_data_reader*, std::less<execution_mode>, std::allocator<std::pair<execution_mode const, lbann::generic_data_reader*> > >&)
rank: 0 :: demangling failed for: main
rank: 0 :: dli_sname == NULL for: 0x10001cd44700 backtrace message was:      /lib64/libc.so.6(+0x24700) [0x10001cd44700]
rank: 0 :: demangling failed for: __libc_start_main

sleeping for two seconds to give all procs a chance to write ...
LBANN: rank 0 of model 0 caught error message:  /g/g92/maruyama/lbann/src/lbann/src/data_readers/data_reader_pilot2_molecular.cpp 53 pilot2_molecular::load() - no features
[unset]: aborting job:
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
[unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=1
:
system msg for write_line failure : Bad file descriptor
[ray53:mpi_rank_0][MPIDI_CH3_Abort] application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0: Bad file descriptor (9)
-------------------------------------------------------
```

**Comment by davidHysom** [comment] 2018-01-03 00:23
Brian's post didn't mention (so far as I can tell) that an exception was thrown.

What you're seeing is some code I recently checked in, that prints a stack trace if an exception is thrown.

To deactivate this, comment out the following in model_zoo/lbann.cpp:


stack_trace::register_handler();


That said, it looks like there's an exception being thrown here:

lbann::pilot2_molecular_reader::load()


LBANN: rank 0 of model 0 caught error message: /g/g92/maruyama/lbann/src/lbann/src/data_readers/data_reader_pilot2_molecular.cpp 53 pilot2_molecular::load() - no features


Hoping this helps ...



________________________________

**Comment by naoyam** [comment] 2018-01-03 00:58
Thanks David. I think this exception should not occur as the model does not even grab GPUs. I guess this would be due to simple misuse of the model or something, but I don't know what "no features" would mean.

**Comment by ndryden** [comment] 2018-01-03 01:02
The error means that the pilot 2 molecular data reader didn't find a features array inside the npz being loaded. I wonder if something happened to the data?

**Comment by davidHysom** [comment] 2018-01-03 02:16
can someone (not me) modify the error msg to be more informative?

________________________________

**Comment by naoyam** [comment] 2018-01-03 23:41
The exception I got was likely because I didn't update CNPY. Fresh build of CNPY removed the problem.

Now I see the original memory behavior reported by Brian. I'll look into it.

**Comment by naoyam** [comment] 2018-01-04 00:10
@timmoon10 Isn't it necessary to call cudaSetDevice before this? 

https://github.com/LLNL/lbann/blob/develop/src/utils/cudnn_wrapper.cpp#L614

I added it and the memory consumption seems to be uniform now.

**Closed** 2018-01-04 01:12 UTC
